## Tarea10
## Moreno Puente Emilia Cristina

Realice las siguientes multiplicaciones matriz-matriz:

In [1]:
import logging
import numpy as np
from sys import stdout
from datetime import datetime
logging.basicConfig(
level=logging.INFO,
format="[%(asctime)s][%(levelname)s] %(message)s",
stream=stdout,
datefmt="%m-%d %H:%M:%S",
)
logging.info(datetime.now())
A = np.array([[2, -3],
[3, -1]])
B = np.array([[1, 5],
[2, 0]])
C = A @ B
print(C)

[01-27 22:40:21][INFO] 2026-01-27 22:40:21.802955
[[-4 10]
 [ 1 15]]


In [2]:
A = np.array([[2, -3, 1],
[4, 3, 0],
[5, 2, -4]])
B = np.array([[0, 1, -2],
[1, 0, -1],
[2, 3, -2]])
C = A @ B
print(C)

[[ -1   5  -3]
 [  3   4 -11]
 [ -6  -7  -4]]


In [3]:
A = np.array([[2, 1, 2],
[-2, 3, 0],
[2, -1, 3]])
B = np.array([[1, -2],
[-4, 1],
[0, 2]])
C = A @ B
print(C)

[[ -2   1]
 [-14   7]
 [  6   1]]


Determine cuáles de las siguientes matrices son no singulares y calcule la inversa de esas matrices:

In [6]:
%load_ext autoreload
%autoreload 2
from src.linear_syst_methods import matriz_inversa
from src.linear_syst_methods import gauss_jordan

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
[01-27 22:41:24][INFO] 2026-01-27 22:41:24.006510


In [7]:
A = np.array([[4, 2, 6],
[3, 0, 7],
[-2, -1, -3]])
gauss_jordan(A)

[01-27 22:41:25][INFO] 
[[ 1  0  1]
 [ 0 -1  2]
 [ 0  0  0]]
[01-27 22:41:25][INFO] 
[[ 1  0  1]
 [ 0  1 -2]
 [ 0  0  0]]


ValueError: No existe solución única.

In [8]:
B = np.array([[1, 2, 0],
[2, 1, -1],
[3, 1, 1]])
gauss_jordan(B)

[01-27 22:41:30][INFO] 
[[ 1  2  0]
 [ 0 -3 -1]
 [ 0 -5  1]]
[01-27 22:41:30][INFO] 
[[1 0 0]
 [0 1 0]
 [0 0 2]]
[01-27 22:41:30][INFO] 
[[1 0 0]
 [0 1 0]
 [0 0 1]]


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [9]:
B = np.array([[1, 2, 0],
[2, 1, -1],
[3, 1, 1]])
matriz_inversa(B)

[01-27 22:41:31][INFO] 
[[ 1.  2.  0.  1.  0.  0.]
 [ 0. -3. -1. -2.  1.  0.]
 [ 0. -5.  1. -3.  0.  1.]]
[01-27 22:41:31][INFO] 
[[ 1.          0.         -0.66666667 -0.33333333  0.66666667  0.        ]
 [-0.          1.          0.33333333  0.66666667 -0.33333333 -0.        ]
 [ 0.          0.          2.66666667  0.33333333 -1.66666667  1.        ]]
[01-27 22:41:31][INFO] 
[[ 1.     0.     0.    -0.25   0.25   0.25 ]
 [-0.     1.     0.     0.625 -0.125 -0.125]
 [ 0.     0.     1.     0.125 -0.625  0.375]]


array([[-0.25 ,  0.25 ,  0.25 ],
       [ 0.625, -0.125, -0.125],
       [ 0.125, -0.625,  0.375]])

In [10]:
C= np.array([[1, 1, -1, 1],
[1, 2, -4, -2],
[2, 1, 1, 5],
[-1, 0, -2, -4]])
gauss_jordan(C)

[01-27 22:41:33][INFO] 
[[ 1  1 -1  1]
 [ 0  1 -3 -3]
 [ 0 -1  3  3]
 [ 0  1 -3 -3]]
[01-27 22:41:33][INFO] 
[[ 1  0  2  4]
 [ 0  1 -3 -3]
 [ 0  0  0  0]
 [ 0  0  0  0]]


ValueError: No existe solución única.

In [11]:
D = np.array([[4, 0, 0, 0],
[6, 7, 0, 0],
[9, 11, 1, 0],
[5, 4, 1, 1]])
gauss_jordan(D)

[01-27 22:41:35][INFO] 
[[ 1  0  0  0]
 [ 0  7  0  0]
 [ 0 11  1  0]
 [ 0  4  1  1]]
[01-27 22:41:35][INFO] 
[[ 1  0  0  0]
 [ 0  1  0  0]
 [ 0  0 -1 -2]
 [ 0  0 -1 -1]]
[01-27 22:41:35][INFO] 
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 2]
 [0 0 0 1]]
[01-27 22:41:35][INFO] 
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [12]:
D = np.array([[4, 0, 0, 0],
[6, 7, 0, 0],
[9, 11, 1, 0],
[5, 4, 1, 1]])
matriz_inversa(D)

[01-27 22:41:38][INFO] 
[[ 1.    0.    0.    0.    0.25  0.    0.    0.  ]
 [ 0.    7.    0.    0.   -1.5   1.    0.    0.  ]
 [ 0.   11.    1.    0.   -2.25  0.    1.    0.  ]
 [ 0.    4.    1.    1.   -1.25  0.    0.    1.  ]]
[01-27 22:41:38][INFO] 
[[ 1.      0.      0.      0.      0.25    0.      0.      0.    ]
 [ 0.      1.      0.25    0.25   -0.3125  0.      0.      0.25  ]
 [ 0.      0.     -1.75   -2.75    1.1875  0.      1.     -2.75  ]
 [ 0.      0.     -1.75   -1.75    0.6875  1.      0.     -1.75  ]]
[01-27 22:41:38][INFO] 
[[ 1.          0.          0.          0.          0.25        0.
   0.          0.        ]
 [ 0.          1.          0.         -0.14285714 -0.14285714  0.
   0.14285714 -0.14285714]
 [-0.         -0.          1.          1.57142857 -0.67857143 -0.
  -0.57142857  1.57142857]
 [ 0.          0.          0.          1.         -0.5         1.
  -1.          1.        ]]
[01-27 22:41:38][INFO] 
[[ 1.          0.          0.          0.          0.25  

array([[ 0.25      ,  0.        ,  0.        ,  0.        ],
       [-0.21428571,  0.14285714,  0.        ,  0.        ],
       [ 0.10714286, -1.57142857,  1.        ,  0.        ],
       [-0.5       ,  1.        , -1.        ,  1.        ]])

Resuelva los sistemas lineales 4 x 4 que tienen la misma matriz de coeficientes:

In [20]:

from src.linear_syst_methods import descomposicion_LU
from src.linear_syst_methods import resolver_LU

In [21]:
A = np.array([[1, -1, 2, -1],
[1, 0, -1, 1],
[2, 1, 3, -4],
[0, -1, 1, -1]])
L1, U1 = descomposicion_LU(np.array(A))
b1 = np.array([6,4,-2,5])
x1 = resolver_LU(L1, U1, b1)
print("Matriz L:")
print(L1)
print("Matriz U:")
print(U1)
print("Solución del sistema Ax=b:")
print(x1)

[01-27 22:43:14][INFO] 
[[ 1. -1.  2. -1.]
 [ 0.  1. -3.  2.]
 [ 0.  3. -1. -2.]
 [ 0. -1.  1. -1.]]
[01-27 22:43:14][INFO] 
[[ 1. -1.  2. -1.]
 [ 0.  1. -3.  2.]
 [ 0.  0.  8. -8.]
 [ 0.  0. -2.  1.]]
[01-27 22:43:14][INFO] 
[[ 1. -1.  2. -1.]
 [ 0.  1. -3.  2.]
 [ 0.  0.  8. -8.]
 [ 0.  0.  0. -1.]]
[01-27 22:43:14][INFO] 
[[ 1. -1.  2. -1.]
 [ 0.  1. -3.  2.]
 [ 0.  0.  8. -8.]
 [ 0.  0.  0. -1.]]
[01-27 22:43:14][INFO] Sustitución hacia adelante
[01-27 22:43:14][INFO] y = 
[[ 6.]
 [-2.]
 [-8.]
 [ 1.]]
[01-27 22:43:14][INFO] Sustitución hacia atrás
[01-27 22:43:14][INFO] i = 2
[01-27 22:43:14][INFO] suma = [8.]
[01-27 22:43:14][INFO] U[i, i] = 8.0
[01-27 22:43:14][INFO] y[i] = [-8.]
[01-27 22:43:14][INFO] i = 1
[01-27 22:43:14][INFO] suma = [4.]
[01-27 22:43:14][INFO] U[i, i] = 1.0
[01-27 22:43:14][INFO] y[i] = [-2.]
[01-27 22:43:14][INFO] i = 0
[01-27 22:43:14][INFO] suma = [3.]
[01-27 22:43:14][INFO] U[i, i] = 1.0
[01-27 22:43:14][INFO] y[i] = [6.]
Matriz L:
[[ 1.    0.    0.    0

In [22]:
L1, U1 = descomposicion_LU(np.array(A))
b1 = np.array([1,1,2,-1])
x1 = resolver_LU(L1, U1, b1)
print("Matriz L:")
print(L1)
print("Matriz U:")
print(U1)
print("Solución del sistema Ax=b:")
print(x1)

[01-27 22:43:16][INFO] 
[[ 1. -1.  2. -1.]
 [ 0.  1. -3.  2.]
 [ 0.  3. -1. -2.]
 [ 0. -1.  1. -1.]]
[01-27 22:43:16][INFO] 
[[ 1. -1.  2. -1.]
 [ 0.  1. -3.  2.]
 [ 0.  0.  8. -8.]
 [ 0.  0. -2.  1.]]
[01-27 22:43:16][INFO] 
[[ 1. -1.  2. -1.]
 [ 0.  1. -3.  2.]
 [ 0.  0.  8. -8.]
 [ 0.  0.  0. -1.]]
[01-27 22:43:16][INFO] 
[[ 1. -1.  2. -1.]
 [ 0.  1. -3.  2.]
 [ 0.  0.  8. -8.]
 [ 0.  0.  0. -1.]]
[01-27 22:43:16][INFO] Sustitución hacia adelante
[01-27 22:43:16][INFO] y = 
[[ 1.]
 [ 0.]
 [ 0.]
 [-1.]]
[01-27 22:43:16][INFO] Sustitución hacia atrás
[01-27 22:43:16][INFO] i = 2
[01-27 22:43:16][INFO] suma = [-8.]
[01-27 22:43:16][INFO] U[i, i] = 8.0
[01-27 22:43:16][INFO] y[i] = [0.]
[01-27 22:43:16][INFO] i = 1
[01-27 22:43:16][INFO] suma = [-1.]
[01-27 22:43:16][INFO] U[i, i] = 1.0
[01-27 22:43:16][INFO] y[i] = [0.]
[01-27 22:43:16][INFO] i = 0
[01-27 22:43:16][INFO] suma = [0.]
[01-27 22:43:16][INFO] U[i, i] = 1.0
[01-27 22:43:16][INFO] y[i] = [1.]
Matriz L:
[[ 1.    0.    0.    0

In [23]:
import sympy as sp
alpha = sp.symbols('alpha')
A = sp.Matrix([
[1, -1, alpha],
[2, 2, 1],
[0, alpha, -sp.Rational(3, 2)]
])
detA = A.det()
print("Determinante:")
sp.pprint(detA)
valores_alpha = sp.solve(detA, alpha)
print("\nValores de alpha que hacen singular la matriz:")
print(valores_alpha)

Determinante:
   2        
2⋅α  - α - 6

Valores de alpha que hacen singular la matriz:
[-3/2, 2]


Resuelva los siguientes sistemas lineale

In [24]:
L1 = np.array(
[[1, 0, 0],
[2, 1, 0],
[-1, 0, 1]]
)
L2 = np.array(
[[2, 3, -1],
[0, -2, 1],
[0, 0, 3]]
)
b1 = np.array([2, -1, 1])
x1 = resolver_LU(L1, L2, b1)
print(f'\nLa solución del sistema es:\n{x1}')

[01-27 22:43:21][INFO] Sustitución hacia adelante
[01-27 22:43:21][INFO] y = 
[[ 2.]
 [-5.]
 [ 3.]]
[01-27 22:43:21][INFO] Sustitución hacia atrás
[01-27 22:43:21][INFO] i = 1
[01-27 22:43:21][INFO] suma = [1.]
[01-27 22:43:21][INFO] U[i, i] = -2
[01-27 22:43:21][INFO] y[i] = [-5.]
[01-27 22:43:21][INFO] i = 0
[01-27 22:43:21][INFO] suma = [8.]
[01-27 22:43:21][INFO] U[i, i] = 2
[01-27 22:43:21][INFO] y[i] = [2.]

La solución del sistema es:
[[-3.]
 [ 3.]
 [ 1.]]


In [25]:
A= np.array([[2, 0, 0],
[-1, 1, 0],
[3, 2, -1]])
B = np.array([[1, 1, 1],
[0, 1, 2],
[0, 0, 1]])
x1 = resolver_LU(L1, L2, b1)
print(f'\nLa solución del sistema es:\n{x1}')

[01-27 22:43:23][INFO] Sustitución hacia adelante
[01-27 22:43:23][INFO] y = 
[[ 2.]
 [-5.]
 [ 3.]]
[01-27 22:43:23][INFO] Sustitución hacia atrás
[01-27 22:43:23][INFO] i = 1
[01-27 22:43:23][INFO] suma = [1.]
[01-27 22:43:23][INFO] U[i, i] = -2
[01-27 22:43:23][INFO] y[i] = [-5.]
[01-27 22:43:23][INFO] i = 0
[01-27 22:43:23][INFO] suma = [8.]
[01-27 22:43:23][INFO] U[i, i] = 2
[01-27 22:43:23][INFO] y[i] = [2.]

La solución del sistema es:
[[-3.]
 [ 3.]
 [ 1.]]


Factorice las siguientes matrices en la descomposición LU mediante el algoritmo de factorización LU con lii = 1 para todas las i

In [26]:
X = np.array(
[[2, -1, 1],
[3, 3, 9],
[3,3, 5]]
)
L1, U1 = descomposicion_LU(X)
print("\nDescomposición de la matriz")
print(f"- Matriz L\n{L1}")
print(f"- Matriz U\n{U1}")

[01-27 22:43:25][INFO] 
[[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   4.5  3.5]]
[01-27 22:43:25][INFO] 
[[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   0.  -4. ]]
[01-27 22:43:25][INFO] 
[[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   0.  -4. ]]

Descomposición de la matriz
- Matriz L
[[1.  0.  0. ]
 [1.5 1.  0. ]
 [1.5 1.  1. ]]
- Matriz U
[[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   0.  -4. ]]


In [27]:
B = np.array([[1.012, -2.132, 3.104],
[-2.132, 4.096, -7.013],
[3.104, -7.013, 0.014]])
L1, U1 = descomposicion_LU(B)
print("\nDescomposición de la matriz")
print(f"- Matriz L\n{L1}")
print(f"- Matriz U\n{U1}")

[01-27 22:43:27][INFO] 
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.         -0.47374308 -9.50656917]]
[01-27 22:43:27][INFO] 
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.          0.         -8.93914077]]
[01-27 22:43:27][INFO] 
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.          0.         -8.93914077]]

Descomposición de la matriz
- Matriz L
[[ 1.          0.          0.        ]
 [-2.10671937  1.          0.        ]
 [ 3.06719368  1.19775553  1.        ]]
- Matriz U
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.          0.         -8.93914077]]


In [28]:
C = np.array([[2, 0, 0, 0],
[1, 1.5, 0, 0],
[0, -3, 0.5, 0],
[2, -2, 1, 1]])
L1, U1 = descomposicion_LU(B)
print("\nDescomposición de la matriz")
print(f"- Matriz L\n{L1}")
print(f"- Matriz U\n{U1}")

[01-27 22:43:30][INFO] 
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.         -0.47374308 -9.50656917]]
[01-27 22:43:30][INFO] 
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.          0.         -8.93914077]]
[01-27 22:43:30][INFO] 
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.          0.         -8.93914077]]

Descomposición de la matriz
- Matriz L
[[ 1.          0.          0.        ]
 [-2.10671937  1.          0.        ]
 [ 3.06719368  1.19775553  1.        ]]
- Matriz U
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.          0.         -8.93914077]]


In [29]:
D = np.array([[2.1756, 4.0231, -2.1732, 5.1967],
[-4.0231, 6.0000, 0, 1.973],
[-1.0000, -5.2107, 1.1111, 0],
[6.0235, 7.0000, 0, -4.1561]])
L1, U1 = descomposicion_LU(D)
print("\nDescomposición de la matriz")
print(f"- Matriz L\n{L1}")
print(f"- Matriz U\n{U1}")

[01-27 22:43:32][INFO] 
[[  2.1756       4.0231      -2.1732       5.1967    ]
 [  0.          13.43948042  -4.01866194  11.58269101]
 [  0.          -3.36150897   0.11220314   2.38862842]
 [  0.          -4.13860216   6.01685521 -18.54400331]]
[01-27 22:43:32][INFO] 
[[ 2.17560000e+00  4.02310000e+00 -2.17320000e+00  5.19670000e+00]
 [ 0.00000000e+00  1.34394804e+01 -4.01866194e+00  1.15826910e+01]
 [ 0.00000000e+00  4.44089210e-16 -8.92952394e-01  5.28571362e+00]
 [ 0.00000000e+00  0.00000000e+00  4.77933394e+00 -1.49771876e+01]]
[01-27 22:43:32][INFO] 
[[ 2.17560000e+00  4.02310000e+00 -2.17320000e+00  5.19670000e+00]
 [ 0.00000000e+00  1.34394804e+01 -4.01866194e+00  1.15826910e+01]
 [ 0.00000000e+00  4.44089210e-16 -8.92952394e-01  5.28571362e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.33134477e+01]]
[01-27 22:43:32][INFO] 
[[ 2.17560000e+00  4.02310000e+00 -2.17320000e+00  5.19670000e+00]
 [ 0.00000000e+00  1.34394804e+01 -4.01866194e+00  1.15826910e+01]
 [ 0.000000

Modifique el algoritmo de eliminación gaussiana de tal forma que se pueda utilizar para resolver un sistema lineal usando la descomposición LU y, a continuación, resuelva los siguientes
sistemas lineales.

In [30]:
A = np.array([[2,-1,1],
[3,3,9],
[3,3,5]])
L1, U1 = descomposicion_LU(np.array(A))
b1 = np.array([1,0,4])
x1 = resolver_LU(L1, U1, b1)
print("Matriz L:")
print(L1)
print("Matriz U:")
print(U1)
print("Solución del sistema Ax=b:")
print(x1)

[01-27 22:43:34][INFO] 
[[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   4.5  3.5]]
[01-27 22:43:34][INFO] 
[[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   0.  -4. ]]
[01-27 22:43:34][INFO] 
[[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   0.  -4. ]]
[01-27 22:43:34][INFO] Sustitución hacia adelante
[01-27 22:43:34][INFO] y = 
[[ 1. ]
 [-1.5]
 [ 4. ]]
[01-27 22:43:34][INFO] Sustitución hacia atrás
[01-27 22:43:34][INFO] i = 1
[01-27 22:43:34][INFO] suma = [-7.5]
[01-27 22:43:34][INFO] U[i, i] = 4.5
[01-27 22:43:34][INFO] y[i] = [-1.5]
[01-27 22:43:34][INFO] i = 0
[01-27 22:43:34][INFO] suma = [-2.33333333]
[01-27 22:43:34][INFO] U[i, i] = 2.0
[01-27 22:43:34][INFO] y[i] = [1.]
Matriz L:
[[1.  0.  0. ]
 [1.5 1.  0. ]
 [1.5 1.  1. ]]
Matriz U:
[[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   0.  -4. ]]
Solución del sistema Ax=b:
[[ 1.66666667]
 [ 1.33333333]
 [-1.        ]]


In [31]:
B = np.array([[1.012, -2.132, 3.104],
[-2.132, 4.096, -7.013],
[3.104, -7.013, 0.014]])
L1, U1 = descomposicion_LU(np.array(B))
b1 = np.array([1.984, -5.049, -3.895])
x1 = resolver_LU(L1, U1, b1)
print("Matriz L:")
print(L1)
print("Matriz U:")
print(U1)
print("Solución del sistema Ax=b:")
print(x1)

[01-27 22:43:37][INFO] 
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.         -0.47374308 -9.50656917]]
[01-27 22:43:37][INFO] 
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.          0.         -8.93914077]]
[01-27 22:43:37][INFO] 
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.          0.         -8.93914077]]
[01-27 22:43:37][INFO] Sustitución hacia adelante
[01-27 22:43:37][INFO] y = 
[[ 1.984     ]
 [-0.86926877]
 [-8.93914077]]
[01-27 22:43:37][INFO] Sustitución hacia atrás
[01-27 22:43:37][INFO] i = 1
[01-27 22:43:37][INFO] suma = [-0.47374308]
[01-27 22:43:37][INFO] U[i, i] = -0.3955256916996053
[01-27 22:43:37][INFO] y[i] = [-0.86926877]
[01-27 22:43:37][INFO] i = 0
[01-27 22:43:37][INFO] suma = [0.972]
[01-27 22:43:37][INFO] U[i, i] = 1.012
[01-27 22:43:37][INFO] y[i] = [1.984]
Matriz L:
[[ 1.          0.          0.        ]
 [-2.10671937  1.          0.        ]
 

In [32]:
D = np.array([[2.1756, 4.0231, -2.1732, 5.1967],
[
-4.0231, 6.0000, 0, 1.973],
[-1.0000, -5.2107, 1.1111, 0],
[6.0235, 7.0000, 0, -4.1561]])
L1, U1 = descomposicion_LU(np.array(D))
b1 = np.array([17.102, -6.1593, 3.0004, 0.0000])
x1 = resolver_LU(L1, U1, b1)
print("Matriz L:")
print(L1)
print("Matriz U:")
print(U1)
print("Solución del sistema Ax=b:")
print(x1)

[01-27 22:43:41][INFO] 
[[  2.1756       4.0231      -2.1732       5.1967    ]
 [  0.          13.43948042  -4.01866194  11.58269101]
 [  0.          -3.36150897   0.11220314   2.38862842]
 [  0.          -4.13860216   6.01685521 -18.54400331]]
[01-27 22:43:41][INFO] 
[[ 2.17560000e+00  4.02310000e+00 -2.17320000e+00  5.19670000e+00]
 [ 0.00000000e+00  1.34394804e+01 -4.01866194e+00  1.15826910e+01]
 [ 0.00000000e+00  4.44089210e-16 -8.92952394e-01  5.28571362e+00]
 [ 0.00000000e+00  0.00000000e+00  4.77933394e+00 -1.49771876e+01]]
[01-27 22:43:41][INFO] 
[[ 2.17560000e+00  4.02310000e+00 -2.17320000e+00  5.19670000e+00]
 [ 0.00000000e+00  1.34394804e+01 -4.01866194e+00  1.15826910e+01]
 [ 0.00000000e+00  4.44089210e-16 -8.92952394e-01  5.28571362e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.33134477e+01]]
[01-27 22:43:41][INFO] 
[[ 2.17560000e+00  4.02310000e+00 -2.17320000e+00  5.19670000e+00]
 [ 0.00000000e+00  1.34394804e+01 -4.01866194e+00  1.15826910e+01]
 [ 0.000000